name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "gh-pages"]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "gtkacz"
          reponame: "is-it-aws"
          token: ${{ secrets.GITHUB_TOKEN }}
